name: Python Linter
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Replace with the actual path to your requirements.txt
    - name: Upgrade Click
      run: pip install --upgrade click
    - name: Python Linter
      uses: sunnysid3up/python-linter@v0.1-beta.7
      with:
        source: UI
        mypy-options: "--ignore-missing-imports --show-error-codes"
