name: Python Linter
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  
    - name: Python Linter
      uses: sunnysid3up/python-linter@master
      with:
        source: "UI"  # Assuming "UI" is the correct path within your repository
        mypy-options: "--ignore-missing-imports --show-error-codes"
        isort-options: "-w 100"
        pylint-options: "--rcfile=setup.cfg"
        django: false
