name: Python Linter
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12  # Specify the Python version you need
    - name: Install dependencies
      run: |
        pip install -m -r requirements.txt  # Replace with the actual path to your requirements.txt
    - name: Python Linter
      uses: sunnysid3up/python-linter@v0.1-beta.7
      with:
        source: UI
